Attempt at ignoring the files missing error in compat-31

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -33,7 +33,7 @@ jobs:
           echo "$RUN_DATA"
           WARNINGS=$(echo "$RUN_DATA" | sed '{/Warning/N;s/\n//;}' |  grep Warning | sed -E 's/^(.*\.el)/- \*\*\1\*\*/')
           LOAD_ERRORS=$(echo "$RUN_DATA" | grep -E "(Cannot load)|(Not found)" | sed 's/^/- /')
-          MISSING_FILES=$(echo "$RUN_DATA" | grep "(file-missing" || : )
+          MISSING_FILES=$(echo "$RUN_DATA" | grep "(file-missing" | grep -v "compat-31" || : )
           echo -e "# Tangle and byte-compile report\n## Errors\n$LOAD_ERRORS\n## Missing files\n$MISSING_FILES\n## Warnings\n$WARNINGS" >> $GITHUB_STEP_SUMMARY
           [ -z "$MISSING_FILES" ] || exit 1
           [ -z "$LOAD_ERRORS" ] || exit 1
@@ -55,7 +55,7 @@ jobs:
           echo "$RUN_DATA"
           WARNINGS=$(echo "$RUN_DATA" | sed '{/Warning/N;s/\n//;}' |  grep Warning | sed -E 's/^(.*\.el)/- \*\*\1\*\*/')
           LOAD_ERRORS=$(echo "$RUN_DATA" | grep -E "(Cannot load)|(Not found)" | sed 's/^/- /')
-          MISSING_FILES=$(echo "$RUN_DATA" | grep "(file-missing" || : )
+          MISSING_FILES=$(echo "$RUN_DATA" | grep "(file-missing"  | grep -v "compat-31" || : )
           echo -e "# Tangle and byte-compile report\n## Errors\n$LOAD_ERRORS\n## Missing files\n$MISSING_FILES\n## Warnings\n$WARNINGS" >> $GITHUB_STEP_SUMMARY
           [ -z "$MISSING_FILES" ] || exit 1
           [ -z "$LOAD_ERRORS" ] || exit 1
